"""
BHAM – Excel Report Generator (styled)
Tre fogli: Modbus Devices / BACnet Devices / IP Hosts
Header colorati, colonne auto-width, freeze pane, filtri.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from data.state import state


# ── Palette ──────────────────────────────────────────────────────────────────
_HDR_CYAN    = PatternFill("solid", fgColor="0E7490")   # Modbus header
_HDR_PURPLE  = PatternFill("solid", fgColor="6D28D9")   # BACnet header
_HDR_ORANGE  = PatternFill("solid", fgColor="C2410C")   # KNX header
_HDR_GREEN   = PatternFill("solid", fgColor="065F46")   # Hosts header
_HDR_FONT    = Font(color="FFFFFF", bold=True)
_ALT_FILL    = PatternFill("solid", fgColor="1F2937")   # alternate row


def _write_sheet(
    wb: openpyxl.Workbook,
    title: str,
    headers: list[str],
    rows: list[list],
    fill: PatternFill,
) -> None:
    ws = wb.create_sheet(title)

    # Header row
    ws.append(headers)
    for col_idx, cell in enumerate(ws[1], start=1):
        cell.fill = fill
        cell.font = _HDR_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # Data rows
    for r_idx, row in enumerate(rows, start=2):
        ws.append(row)
        if r_idx % 2 == 0:
            for cell in ws[r_idx]:
                cell.fill = _ALT_FILL

    # Auto-width
    for col_idx, col_cells in enumerate(ws.columns, start=1):
        max_len = max((len(str(c.value or "")) for c in col_cells), default=8)
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 4, 50)

    # Freeze header + filters
    ws.freeze_panes = ws["A2"]
    ws.auto_filter.ref = ws.dimensions


def generate_excel(filepath: str) -> str:
    """Generate styled Excel report. Returns *filepath*."""
    wb = openpyxl.Workbook()
    # Remove default sheet
    wb.remove(wb.active)

    # ── Sheet 1: Modbus ──────────────────────────────────────────────────────
    mb_headers = ["Slave ID", "Protocol", "IP", "TCP Port",
                  "Serial Port", "Baudrate", "Response ms", "Discovered At"]
    mb_rows = []
    for d in state.modbus_devices.values():
        mb_rows.append([
            d.slave_id,
            d.protocol.value,
            d.ip or "",
            d.tcp_port if d.ip else "",
            d.serial_params.port if d.serial_params else "",
            d.serial_params.baudrate if d.serial_params else "",
            round(d.response_time_ms, 2) if d.response_time_ms else "",
            str(d.discovered_at)[:19],
        ])
    _write_sheet(wb, "Modbus Devices", mb_headers, mb_rows, _HDR_CYAN)

    # ── Sheet 2: BACnet ──────────────────────────────────────────────────────
    bn_headers = ["Device ID", "Address", "Vendor ID", "Vendor Name",
                  "Model Name", "FW Revision", "SW Version", "Discovered At"]
    bn_rows = []
    for d in state.bacnet_devices.values():
        bn_rows.append([
            d.device_id,
            d.address,
            d.vendor_id or "",
            d.vendor_name or "",
            d.model_name or "",
            d.firmware_revision or "",
            d.application_software_version or "",
            str(d.discovered_at)[:19],
        ])
    _write_sheet(wb, "BACnet Devices", bn_headers, bn_rows, _HDR_PURPLE)

    # ── Sheet 3: KNX Devices ─────────────────────────────────────────────────
    knx_headers = ["Individual Address", "IP Address", "Port", "Device Name",
                   "Serial Number", "MAC", "Medium", "Discovered At"]
    knx_rows = []
    for k in state.knx_devices.values():
        knx_rows.append([
            k.individual_address,
            k.ip_address,
            k.port,
            k.device_name or "",
            k.serial_number or "",
            k.mac_address or "",
            k.medium,
            str(k.discovered_at)[:19],
        ])
    _write_sheet(wb, "KNX Devices", knx_headers, knx_rows, _HDR_ORANGE)

    # ── Sheet 4: IP Hosts ────────────────────────────────────────────────────
    ip_headers = ["IP Address", "MAC", "Hostname", "Open Ports",
                  "Protocol Hints", "First Seen", "Last Seen"]
    ip_rows = []
    for h in state.ip_hosts.values():
        ip_rows.append([
            h.ip,
            h.mac or "",
            h.hostname or "",
            ", ".join(str(p) for p in h.open_ports),
            ", ".join(p.value for p in h.protocol_hints),
            str(h.first_seen)[:19],
            str(h.last_seen)[:19],
        ])
    _write_sheet(wb, "IP Hosts", ip_headers, ip_rows, _HDR_GREEN)

    # ── Metadata sheet ───────────────────────────────────────────────────────
    ws_meta = wb.create_sheet("Report Info")
    ws_meta.append(["Generated by", "BHAM – BACS Help Auto Mapper"])
    ws_meta.append(["Generated at", str(datetime.now(timezone.utc))[:19] + " UTC"])
    ws_meta.append(["Modbus devices", len(mb_rows)])
    ws_meta.append(["BACnet devices", len(bn_rows)])
    ws_meta.append(["KNX devices", len(knx_rows)])
    ws_meta.append(["IP hosts", len(ip_rows)])

    wb.save(filepath)
    return filepath
